### ISSUE TITLE
represent state as enum in blips

### ISSUE THREAD

**Issue by anoff** [anoff/devradar#54]
To improve filesize and portability the state and categories should be represented in enum style where the meta fields are only referenced by their index.

```toml
[[blips]]
category = "Frameworks"
title = "Javascript"
state = "Advanced"

  [[blips.changes]]
  date = "2019-06"
  newState = "Advanced"
```

⬇

```toml
[[blips]]
category = 3
title = "Javascript"
state = 2

  [[blips.changes]]
  date = "2019-06"
  newState = 2
```
